package com.tianjian.comm.bean;

/**
 * CommConfigLocationGroup generated by MyEclipse Persistence Tools
 */
public class CommConfigLocationGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3614775780497657785L;
	// Fields
	private String id;
	private Long seqNo;
	private String itemCode;
	private String itemName;
	private String inputCode;
	private String comments;
	private String commClvId;

	// Constructors
	/** default constructor */
	public CommConfigLocationGroup() {}

	/** full constructor */
	public CommConfigLocationGroup(Long seqNo, String itemCode, String itemName, String inputCode, String comments, String commClvId) {
		this.seqNo = seqNo;
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.inputCode = inputCode;
		this.comments = comments;
		this.commClvId = commClvId;
	}

	// Property accessors
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getInputCode() {
		return this.inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getCommClvId() {
		return this.commClvId;
	}

	public void setCommClvId(String commClvId) {
		this.commClvId = commClvId;
	}
}