package com.tianjian.comm.bean;


/**
 * CommDictPublicClass generated by MyEclipse Persistence Tools
 */
public class CommDictPublicClass implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7446671571603870174L;
	// Fields
	
	/**类别代码*/
	private String classCode;
	/**类别名称*/
	private String className;
	/**输入码*/
	private String inputCode;
	/**备注*/
	private String comments;
	/**序号*/
	private Long seqNo;
	/** */
	

	// Constructors
	/** default constructor */
	public CommDictPublicClass() {}

	/** full constructor */
	public CommDictPublicClass(String classCode, String className, String inputCode, String comments, Long seqNo) {
		this.classCode = classCode;
		this.className = className;
		this.inputCode = inputCode;
		this.comments = comments;
		this.seqNo = seqNo;
	}

	
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getInputCode() {
		return this.inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

}