package com.tianjian.comm.bean;

import java.util.Date;

/**
 * CommTableDateId generated by MyEclipse Persistence Tools
 */
public class CommTableDateId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5057247929798504880L;
	// Fields
	/**id */
	private Long id;
	/**表名 */
	private String tableName;
	/**列名 */
	private String columnName;
	/**日期 */
	private Date seqDate;
	/**序号 */
	private Long idvalue;
	/**备注 */
	private String comments;

	// Constructors
	/** default constructor */
	public CommTableDateId() {}

	/** minimal constructor */
	public CommTableDateId(Long id) {
		this.id = id;
	}

	/** full constructor */
	public CommTableDateId(Long id, String tableName, String columnName, Date seqDate, Long idvalue, String comments) {
		this.id = id;
		this.tableName = tableName;
		this.columnName = columnName;
		this.seqDate = seqDate;
		this.idvalue = idvalue;
		this.comments =comments;
	}

	// Property accessors
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	public Date getSeqDate() {
		return this.seqDate;
	}

	public void setSeqDate(Date seqDate) {
		this.seqDate = seqDate;
	}

	public Long getIdvalue() {
		return this.idvalue;
	}

	public void setIdvalue(Long idvalue) {
		this.idvalue = idvalue;
	}

	
	public String getComments() {
		return comments;
	}

	
	public void setComments(String comments) {
		this.comments = comments;
	}

	 
}