package com.tianjian.comm.bean;

import java.util.Date;

/**
 * CommConfigAbo generated by MyEclipse Persistence Tools
 */
public class CommIHEFacility implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2879739394259703580L;
	/**
	 * 
	 */

	// Fields
	
	private String id;
	private long seqNo;
	private String facilityUniversalId;
	private String facilityUniversalIdType;
	private String facilityNamespaceId;
	private Date dateCreated;
	private String creatorId;

	// Constructors
	/** default constructor */
	public CommIHEFacility() {}

	/** full constructor */
	public CommIHEFacility(String id,String facilityUniversalId, Long seqNo, String facilityUniversalIdType, String facilityNamespaceId, String creatorId,Date dateCreated) {
		this.id = id;
		this.seqNo = seqNo;
		this.facilityUniversalId = facilityUniversalId;
		this.facilityUniversalIdType = facilityUniversalIdType;
		this.facilityNamespaceId = facilityNamespaceId;
		this.dateCreated = dateCreated;
		this.creatorId = creatorId;

	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public long getSeqNo() {
		return seqNo;
	}

	public void setSeqNo(long seqNo) {
		this.seqNo = seqNo;
	}

	public String getFacilityUniversalId() {
		return facilityUniversalId;
	}

	public void setFacilityUniversalId(String facilityUniversalId) {
		this.facilityUniversalId = facilityUniversalId;
	}

	public String getFacilityUniversalIdType() {
		return facilityUniversalIdType;
	}

	public void setFacilityUniversalIdType(String facilityUniversalIdType) {
		this.facilityUniversalIdType = facilityUniversalIdType;
	}

	public String getFacilityNamespaceId() {
		return facilityNamespaceId;
	}

	public void setFacilityNamespaceId(String facilityNamespaceId) {
		this.facilityNamespaceId = facilityNamespaceId;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	// Property accessors
	
}