package com.tianjian.comm.bean;

/**
 * CommConfigCountry generated by MyEclipse Persistence Tools
 */
public class CommConfigCountry implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 36791399098717705L;
	// Fields
	/**代码*/
	private String itemCode;
	/**序号*/
	private Long seqNo;
	/**名称*/
	private String itemName;
	/**输入码*/
	private String inputCode;
	/**备注*/
	private String comments;

	// Constructors
	/** default constructor */
	public CommConfigCountry() {}

	/** minimal constructor */
	public CommConfigCountry(String itemCode) {
		this.itemCode = itemCode;
	}

	/** full constructor */
	public CommConfigCountry(String itemCode, Long seqNo, String itemName, String inputCode, String comments) {
		this.itemCode = itemCode;
		this.seqNo = seqNo;
		this.itemName = itemName;
		this.inputCode = inputCode;
		this.comments = comments;
	}

	// Property accessors
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getInputCode() {
		return this.inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
}