package com.tianjian.comm.bean;

/**
 * CommDiseaseValueSet generated by MyEclipse Persistence Tools
 */

public class CommDiseaseValueSet implements java.io.Serializable {

	// Fields

	private String hspConfigBaseinfoId;
	private String diseaseId;
	private String diseaseName;
	private String diagnose1;
	private String diagnose2;
	private String death3;
	private String death4;
	private String sdotId;
	private String isImp;
	private String isDis;
	public String getHspConfigBaseinfoId() {
		return hspConfigBaseinfoId;
	}
	public void setHspConfigBaseinfoId(String hspConfigBaseinfoId) {
		this.hspConfigBaseinfoId = hspConfigBaseinfoId;
	}
	public String getDiseaseId() {
		return diseaseId;
	}
	public void setDiseaseId(String diseaseId) {
		this.diseaseId = diseaseId;
	}
	public String getDiseaseName() {
		return diseaseName;
	}
	public void setDiseaseName(String diseaseName) {
		this.diseaseName = diseaseName;
	}
	public String getDiagnose1() {
		return diagnose1;
	}
	public void setDiagnose1(String diagnose1) {
		this.diagnose1 = diagnose1;
	}
	public String getDiagnose2() {
		return diagnose2;
	}
	public void setDiagnose2(String diagnose2) {
		this.diagnose2 = diagnose2;
	}
	public String getDeath3() {
		return death3;
	}
	public void setDeath3(String death3) {
		this.death3 = death3;
	}
	public String getDeath4() {
		return death4;
	}
	public void setDeath4(String death4) {
		this.death4 = death4;
	}
	public String getSdotId() {
		return sdotId;
	}
	public void setSdotId(String sdotId) {
		this.sdotId = sdotId;
	}
	public String getIsImp() {
		return isImp;
	}
	public void setIsImp(String isImp) {
		this.isImp = isImp;
	}
	public String getIsDis() {
		return isDis;
	}
	public void setIsDis(String isDis) {
		this.isDis = isDis;
	}
	public CommDiseaseValueSet() {
		super();
		// TODO Auto-generated constructor stub
	}
	public CommDiseaseValueSet(String hspConfigBaseinfoId, String diseaseId,
			String diseaseName, String diagnose1, String diagnose2,
			String death3, String death4, String sdotId, String isImp,
			String isDis) {
		super();
		this.hspConfigBaseinfoId = hspConfigBaseinfoId;
		this.diseaseId = diseaseId;
		this.diseaseName = diseaseName;
		this.diagnose1 = diagnose1;
		this.diagnose2 = diagnose2;
		this.death3 = death3;
		this.death4 = death4;
		this.sdotId = sdotId;
		this.isImp = isImp;
		this.isDis = isDis;
	}
	 
	

}