package com.tianjian.comm.bean;

/**
 * CommConfigInputDict generated by MyEclipse Persistence Tools
 */
public class CommConfigInputDict implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5711868838906100195L;
	// Fields
	private String itemCode;
	private String itemName;
	private String inputCode;
	private String inputCodeWb;
	private String inputCode1;
	private String inputCode2;
	private String comments;

	// Constructors
	/** default constructor */
	public CommConfigInputDict() {}

	/** minimal constructor */
	public CommConfigInputDict(String itemCode) {
		this.itemCode = itemCode;
	}

	/** full constructor */
	public CommConfigInputDict(String itemCode, String itemName, String inputCode, String inputCodeWb, String inputCode1, String inputCode2, String comments) {
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.inputCode = inputCode;
		this.inputCodeWb = inputCodeWb;
		this.inputCode1 = inputCode1;
		this.inputCode2 = inputCode2;
		this.comments = comments;
	}

	// Property accessors
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getInputCode() {
		return this.inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getInputCodeWb() {
		return this.inputCodeWb;
	}

	public void setInputCodeWb(String inputCodeWb) {
		this.inputCodeWb = inputCodeWb;
	}

	public String getInputCode1() {
		return this.inputCode1;
	}

	public void setInputCode1(String inputCode1) {
		this.inputCode1 = inputCode1;
	}

	public String getInputCode2() {
		return this.inputCode2;
	}

	public void setInputCode2(String inputCode2) {
		this.inputCode2 = inputCode2;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
}