package com.tianjian.comm.bean;

/**
 * CommConfigGbDrugclass generated by MyEclipse Persistence Tools
 */

public class CommConfigGbDrugclass implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -7938633885279854336L;
	private String itemCode;
	private String itemName;
	private String inputCode;
	private Long levelFlag;
	private String parentId;
	private String comments;
	private Long seqNo;

	// Constructors

	/** default constructor */
	public CommConfigGbDrugclass() {
	}

	/** full constructor */
	public CommConfigGbDrugclass(String itemName, String inputCode,
			Long levelFlag, String parentId, String comments, Long seqNo) {
		this.itemName = itemName;
		this.inputCode = inputCode;
		this.levelFlag = levelFlag;
		this.parentId = parentId;
		this.comments = comments;
		this.seqNo = seqNo;
	}

	// Property accessors

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getInputCode() {
		return this.inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public Long getLevelFlag() {
		return this.levelFlag;
	}

	public void setLevelFlag(Long levelFlag) {
		this.levelFlag = levelFlag;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

}