package com.tianjian.comm.bean;

/**
 * CommConfigLocationVillage generated by MyEclipse Persistence Tools
 */

public class CommConfigLocationVillage implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -5112810166073316128L;
	private String id;
	private String itemCode;
	private String itemName;
	private String inputCode;
	private String commCltId;
	private Long villagerNum;//总人数
	private Long familyNum;//总家庭数
	private String contactPersonName;//联系人姓名
	private String phohe;//联系电话
	private String comments;
	private Long seqNo;

	// Constructors

	/** default constructor */
	public CommConfigLocationVillage() {
	}

	/** full constructor */
	public CommConfigLocationVillage(String itemCode, String itemName,
			String inputCode, String commCltId, Long villagerNum,
			Long familyNum, String contactPersonName, String phohe,
			String comments, Long seqNo) {
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.inputCode = inputCode;
		this.commCltId = commCltId;
		this.villagerNum = villagerNum;
		this.familyNum = familyNum;
		this.contactPersonName = contactPersonName;
		this.phohe = phohe;
		this.comments = comments;
		this.seqNo = seqNo;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getInputCode() {
		return this.inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getCommCltId() {
		return this.commCltId;
	}

	public void setCommCltId(String commCltId) {
		this.commCltId = commCltId;
	}

	public Long getVillagerNum() {
		return this.villagerNum;
	}

	public void setVillagerNum(Long villagerNum) {
		this.villagerNum = villagerNum;
	}

	public Long getFamilyNum() {
		return this.familyNum;
	}

	public void setFamilyNum(Long familyNum) {
		this.familyNum = familyNum;
	}

	public String getContactPersonName() {
		return this.contactPersonName;
	}

	public void setContactPersonName(String contactPersonName) {
		this.contactPersonName = contactPersonName;
	}

	public String getPhohe() {
		return this.phohe;
	}

	public void setPhohe(String phohe) {
		this.phohe = phohe;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

}