package com.tianjian.comm.bean;

import java.util.Date;


/**
 * CommConfigAbo generated by MyEclipse Persistence Tools
 */
public class CommMenuHelp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4439567953256567045L;
	// Fields
	private String id;
	private Long seqNo;
	private String menuName;
	private String menuHelpTitle;
	private String menuHelpContent;
	private String menuHelpComment;
	private String menuFlag;
	private Date createDate;
	private String createUserId;
	private String createUserName;

	// Constructors
	/** default constructor */
	public CommMenuHelp() {}

	/** full constructor */
	public CommMenuHelp(String id, Long seqNo, String menuName, String menuHelpTitle, String menuHelpContent, 
			String menuHelpComment,String menuFlag,String createUserId,String createUserName) {
		this.id = id;
		this.seqNo = seqNo;
		this.menuName = menuName;
		this.menuHelpTitle = menuHelpTitle;
		this.menuHelpContent = menuHelpContent;
		this.menuHelpComment = menuHelpComment;
		this.menuFlag = menuFlag;
		this.createUserId = createUserId;
		this.createUserName = createUserName;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getSeqNo() {
		return seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

	public String getMenuName() {
		return menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuHelpTitle() {
		return menuHelpTitle;
	}

	public void setMenuHelpTitle(String menuHelpTitle) {
		this.menuHelpTitle = menuHelpTitle;
	}

	public String getMenuHelpContent() {
		return menuHelpContent;
	}

	public void setMenuHelpContent(String menuHelpContent) {
		this.menuHelpContent = menuHelpContent;
	}

	public String getMenuHelpComment() {
		return menuHelpComment;
	}

	public void setMenuHelpComment(String menuHelpComment) {
		this.menuHelpComment = menuHelpComment;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public String getMenuFlag() {
		return menuFlag;
	}

	public void setMenuFlag(String menuFlag) {
		this.menuFlag = menuFlag;
	}


	// Property accessors
	
}