package com.tianjian.comm.bean;

/**
 * CommDictPublicChar generated by MyEclipse Persistence Tools
 */
public class CommDictPublicInt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4127252212483225490L;
	// Fields
	/**字典ID*/
	private String id;
	/**字典类别*/
	private String classCode;
	/**字典代码*/
	private String dictCode;
	/**字典名称*/
	private Long dictValue;
	/**输入码*/
	private String inputCode;
	/**备注*/
	private String comments;
	/**序号*/
	private Long seqNo;
	/**字典类别*/
	private com.tianjian.comm.bean.CommDictPublicClass classCodeObject;
	// Constructors
	/** default constructor */
	public CommDictPublicInt() {}

	/** full constructor */
	public CommDictPublicInt(String classCode, String dictCode, Long dictValue, String inputCode, String comments, Long seqNo,com.tianjian.comm.bean.CommDictPublicClass classCodeObject) {
		this.classCode = classCode;
		this.dictCode = dictCode;
		this.dictValue = dictValue;
		this.inputCode = inputCode;
		this.comments = comments;
		this.seqNo = seqNo;
		this.classCodeObject = classCodeObject;
	}

	// Property accessors
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}



	public String getInputCode() {
		return this.inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

	
	public String getClassCode() {
		return classCode;
	}

	
	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	
	public String getDictCode() {
		return dictCode;
	}

	
	public void setDictCode(String dictCode) {
		this.dictCode = dictCode;
	}

	
	public Long getDictValue() {
		return dictValue;
	}

	
	public void setDictValue(Long dictValue) {
		this.dictValue = dictValue;
	}

	
	public com.tianjian.comm.bean.CommDictPublicClass getClassCodeObject() {
		return classCodeObject;
	}

	
	public void setClassCodeObject(com.tianjian.comm.bean.CommDictPublicClass classCodeObject) {
		this.classCodeObject = classCodeObject;
	}

	
	
}