package com.tianjian.comm.bean;

/**
 * CommConfigLocation generated by MyEclipse Persistence Tools
 */
public class CommConfigLocation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8452795751835080965L;
	// Fields
	private String id;
	private String itemCode;
	private String itemName;
	private String inputCode;
	private Long levelFlag;
	private String parentId;
	private String comments;
	private Long seqNo;
	private com.tianjian.comm.bean.CommConfigLocation parentIdObject;

	// Constructors
	/** default constructor */
	public CommConfigLocation() {}

	/** full constructor */
	public CommConfigLocation(String itemCode, String itemName, String inputCode, Long levelFlag, String parentId, String comments, Long seqNo,com.tianjian.comm.bean.CommConfigLocation parentIdObject) {
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.inputCode = inputCode;
		this.levelFlag = levelFlag;
		this.parentId = parentId;
		this.comments = comments;
		this.seqNo = seqNo;
		this.parentIdObject = parentIdObject;
	}

	// Property accessors
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getInputCode() {
		return this.inputCode;
	}

	public void setInputCode(String inputCode) {
		this.inputCode = inputCode;
	}

	public Long getLevelFlag() {
		return this.levelFlag;
	}

	public void setLevelFlag(Long levelFlag) {
		this.levelFlag = levelFlag;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Long seqNo) {
		this.seqNo = seqNo;
	}

	
	public com.tianjian.comm.bean.CommConfigLocation getParentIdObject() {
		return parentIdObject;
	}

	
	public void setParentIdObject(com.tianjian.comm.bean.CommConfigLocation parentIdObject) {
		this.parentIdObject = parentIdObject;
	}
}