package com.tianjian.security.bean;

import java.util.Date;



/**
 * SecurityConfigMenus generated by MyEclipse Persistence Tools
 */

public class SecurityXtSysLog implements java.io.Serializable {

	// Fields
	/**
	 * 
	 */
	private static final long serialVersionUID = -8900806184202653910L;
	
	private String id;
	/**模块*/
    private Date logTime;
    private String logLevel;
    private String logAction;
    private String logMessage;
	/** default constructor */
	public SecurityXtSysLog() {
	}
	

	/** full constructor */
	public SecurityXtSysLog(String id,Date logTime,String logLevel,String logAction,String logMessage) {
		this.id = id;
		this.logTime = logTime;
		this.logLevel = logLevel;
		this.logAction = logAction;
		this.logMessage = logMessage;
	}
	// Property accessors

	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public Date getLogTime() {
		return logTime;
	}


	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}


	public String getLogLevel() {
		return logLevel;
	}


	public void setLogLevel(String logLevel) {
		this.logLevel = logLevel;
	}


	public String getLogAction() {
		return logAction;
	}


	public void setLogAction(String logAction) {
		this.logAction = logAction;
	}


	public String getLogMessage() {
		return logMessage;
	}


	public void setLogMessage(String logMessage) {
		this.logMessage = logMessage;
	}

}