package com.tianjian.security.bean;

/**
 * SecurityRoleVsMenus generated by MyEclipse Persistence Tools
 */

public class SecurityRoleVsMenus implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -2718926629837830856L;
	private String id;
	/**角色*/
	private SecurityConfigRoles securityConfigRoles;
	/**菜单*/
	private SecurityConfigMenus securityConfigMenus;
	/**备注*/
	private String comments;
	/**角色ID*/
	private String securityConfigRolesId;
	/**菜单ID*/
	private String securityConfigMenusId;
	// Constructors

	/** default constructor */
	public SecurityRoleVsMenus() {
	}

	/** minimal constructor */
	public SecurityRoleVsMenus(SecurityConfigRoles securityConfigRoles,
			SecurityConfigMenus securityConfigMenus) {
		this.securityConfigRoles = securityConfigRoles;
		this.securityConfigMenus = securityConfigMenus;
	}

	/** full constructor */
	public SecurityRoleVsMenus(SecurityConfigRoles securityConfigRoles,
			SecurityConfigMenus securityConfigMenus, String comments) {
		this.securityConfigRoles = securityConfigRoles;
		this.securityConfigMenus = securityConfigMenus;
		this.comments = comments;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SecurityConfigRoles getSecurityConfigRoles() {
		return this.securityConfigRoles;
	}

	public void setSecurityConfigRoles(SecurityConfigRoles securityConfigRoles) {
		this.securityConfigRoles = securityConfigRoles;
	}

	public SecurityConfigMenus getSecurityConfigMenus() {
		return this.securityConfigMenus;
	}

	public void setSecurityConfigMenus(SecurityConfigMenus securityConfigMenus) {
		this.securityConfigMenus = securityConfigMenus;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getSecurityConfigRolesId() {
		return securityConfigRolesId;
	}

	public void setSecurityConfigRolesId(String securityConfigRolesId) {
		this.securityConfigRolesId = securityConfigRolesId;
	}

	public String getSecurityConfigMenusId() {
		return securityConfigMenusId;
	}

	public void setSecurityConfigMenusId(String securityConfigMenusId) {
		this.securityConfigMenusId = securityConfigMenusId;
	}

}